// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Asynchronous BAML client with function-object pattern.

use crate::baml_client::{runtime::{get_runtime, FunctionOptions}, stream_types, types};
use baml::{AsyncStreamingCall, BamlEncode, BamlError};

// =============================================================================
// Convenience Builder Methods Macro
// =============================================================================

/// Implements convenience builder methods that delegate to `with_options`.
/// Requires the type to have:
/// - `options: FunctionOptions` field
/// - `fn with_options(&self, options: FunctionOptions) -> Self` method
macro_rules! impl_options_convenience_methods {
    ($name:ident) => {
        impl $name {
            pub fn with_collector(&self, collector: &baml::Collector) -> Self {
                self.with_options(self.options.clone().with_collector(collector))
            }

            pub fn with_collectors(&self, collectors: &[baml::Collector]) -> Self {
                self.with_options(self.options.clone().with_collectors(collectors))
            }

            pub fn with_cancellation_token(&self, token: Option<baml::CancellationToken>) -> Self {
                self.with_options(self.options.clone().with_cancellation_token(token))
            }

            pub fn with_type_builder(&self, tb: &super::super::type_builder::TypeBuilder) -> Self {
                self.with_options(self.options.clone().with_type_builder(tb))
            }

            pub fn with_env_var(&self, key: impl Into<String>, value: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_env_var(key, value))
            }

            pub fn with_tag(&self, key: impl Into<String>, value: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_tag(key, value))
            }

            pub fn with_client(&self, client_name: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_client(client_name))
            }

            pub fn with_client_registry(&self, registry: &baml::ClientRegistry) -> Self {
                self.with_options(self.options.clone().with_client_registry(registry))
            }
        }
    };
}

// =============================================================================
// Function Struct Macro (generates per-function struct with async methods)
// =============================================================================

macro_rules! baml_function_async {
    ($name:ident($($param:ident : $ptype:ty),* $(,)?) -> ($stream_ret:ty, $final_ret:ty)) => {
        #[derive(Clone)]
        pub struct $name {
            pub(crate) options: FunctionOptions,
        }

        impl $name {
            pub const fn new() -> Self {
                Self { options: FunctionOptions::new() }
            }

            fn with_options(&self, options: FunctionOptions) -> Self {
                Self { options }
            }

            // Terminal methods (async)
            pub async fn call(&self, $($param: $ptype),*) -> Result<$final_ret, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*;
                get_runtime().call_function_async(stringify!($name), &args).await
            }

            pub fn stream(&self, $($param: $ptype),*) -> Result<AsyncStreamingCall<$stream_ret, $final_ret>, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*;
                get_runtime().call_function_stream_async(stringify!($name), &args)
            }

            pub fn parse(&self, response: &str) -> Result<$final_ret, BamlError> {
                get_runtime().parse(stringify!($name), response, false)
            }

            pub fn parse_stream(&self, response: &str) -> Result<$stream_ret, BamlError> {
                get_runtime().parse(stringify!($name), response, true)
            }
        }

        // Builder convenience methods (separate impl block via macro)
        impl_options_convenience_methods!($name);
    };
}

// =============================================================================
// Generate function structs
// =============================================================================



baml_function_async!(AnalyzeTestResults(test_output: impl AsRef<str> + BamlEncode, code_context: Option<impl AsRef<str> + BamlEncode>, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::TestAnalysis, types::TestAnalysis));


baml_function_async!(BreakdownTask(task: &types::Task, context: impl AsRef<str> + BamlEncode, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::TaskBreakdown, types::TaskBreakdown));


baml_function_async!(CreatePlan(objective: impl AsRef<str> + BamlEncode, research_context: impl AsRef<str> + BamlEncode, constraints: Option<impl AsRef<str> + BamlEncode>, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::ImplementationPlan, types::ImplementationPlan));


baml_function_async!(DecideNextAction(completed_tasks: &[String], current_task: Option<impl AsRef<str> + BamlEncode>, remaining_tasks: &[String], blockers: &[String], recent_output: impl AsRef<str> + BamlEncode, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::LoopDecision, types::LoopDecision));


baml_function_async!(ExplainCode(code: impl AsRef<str> + BamlEncode, file_path: impl AsRef<str> + BamlEncode, question: Option<impl AsRef<str> + BamlEncode>, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::CodeExplanation, types::CodeExplanation));


baml_function_async!(GenerateCommitMessage(diff: impl AsRef<str> + BamlEncode, context: Option<impl AsRef<str> + BamlEncode>, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::CommitMessage, types::CommitMessage));


baml_function_async!(GenerateHandoff(from_stage: impl AsRef<str> + BamlEncode, to_stage: impl AsRef<str> + BamlEncode, work_done: impl AsRef<str> + BamlEncode, outputs: impl AsRef<str> + BamlEncode, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::StageHandoff, types::StageHandoff));


baml_function_async!(GeneratePRDescription(commits: impl AsRef<str> + BamlEncode, diff_summary: impl AsRef<str> + BamlEncode, related_issues: Option<impl AsRef<str> + BamlEncode>, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::PRDescription, types::PRDescription));


baml_function_async!(ImplementTask(task_id: impl AsRef<str> + BamlEncode, task_description: impl AsRef<str> + BamlEncode, relevant_code: impl AsRef<str> + BamlEncode, acceptance_criteria: &[String], additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::ImplementationResult, types::ImplementationResult));


baml_function_async!(ResearchTopic(topic: impl AsRef<str> + BamlEncode, codebase_context: impl AsRef<str> + BamlEncode, constraints: Option<impl AsRef<str> + BamlEncode>, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::ResearchFindings, types::ResearchFindings));


baml_function_async!(ReviewCode(code_diff: impl AsRef<str> + BamlEncode, context: impl AsRef<str> + BamlEncode, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::CodeReviewFeedback, types::CodeReviewFeedback));


baml_function_async!(SelectSubagent(task_title: impl AsRef<str> + BamlEncode, task_description: impl AsRef<str> + BamlEncode, available_context: impl AsRef<str> + BamlEncode, additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::SubagentSelection, types::SubagentSelection));


baml_function_async!(ValidateImplementation(task_description: impl AsRef<str> + BamlEncode, changes_made: impl AsRef<str> + BamlEncode, test_results: Option<impl AsRef<str> + BamlEncode>, acceptance_criteria: &[String], additional_context: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::ValidationResult, types::ValidationResult));


// =============================================================================
// Client Struct
// =============================================================================

#[derive(Clone)]
pub struct BamlAsyncClient {
    options: FunctionOptions,
    
    pub AnalyzeTestResults: AnalyzeTestResults,
    
    pub BreakdownTask: BreakdownTask,
    
    pub CreatePlan: CreatePlan,
    
    pub DecideNextAction: DecideNextAction,
    
    pub ExplainCode: ExplainCode,
    
    pub GenerateCommitMessage: GenerateCommitMessage,
    
    pub GenerateHandoff: GenerateHandoff,
    
    pub GeneratePRDescription: GeneratePRDescription,
    
    pub ImplementTask: ImplementTask,
    
    pub ResearchTopic: ResearchTopic,
    
    pub ReviewCode: ReviewCode,
    
    pub SelectSubagent: SelectSubagent,
    
    pub ValidateImplementation: ValidateImplementation,
    
}

impl BamlAsyncClient {
    pub const fn new() -> Self {
        Self {
            options: FunctionOptions::new(),
            
            AnalyzeTestResults: AnalyzeTestResults::new(),
            
            BreakdownTask: BreakdownTask::new(),
            
            CreatePlan: CreatePlan::new(),
            
            DecideNextAction: DecideNextAction::new(),
            
            ExplainCode: ExplainCode::new(),
            
            GenerateCommitMessage: GenerateCommitMessage::new(),
            
            GenerateHandoff: GenerateHandoff::new(),
            
            GeneratePRDescription: GeneratePRDescription::new(),
            
            ImplementTask: ImplementTask::new(),
            
            ResearchTopic: ResearchTopic::new(),
            
            ReviewCode: ReviewCode::new(),
            
            SelectSubagent: SelectSubagent::new(),
            
            ValidateImplementation: ValidateImplementation::new(),
            
        }
    }

    /// Apply options to all functions. Returns a new client with the options set.
    pub fn with_options(&self, options: FunctionOptions) -> Self {
        Self {
            options: options.clone(),
            
            AnalyzeTestResults: AnalyzeTestResults { options: options.clone() },
            
            BreakdownTask: BreakdownTask { options: options.clone() },
            
            CreatePlan: CreatePlan { options: options.clone() },
            
            DecideNextAction: DecideNextAction { options: options.clone() },
            
            ExplainCode: ExplainCode { options: options.clone() },
            
            GenerateCommitMessage: GenerateCommitMessage { options: options.clone() },
            
            GenerateHandoff: GenerateHandoff { options: options.clone() },
            
            GeneratePRDescription: GeneratePRDescription { options: options.clone() },
            
            ImplementTask: ImplementTask { options: options.clone() },
            
            ResearchTopic: ResearchTopic { options: options.clone() },
            
            ReviewCode: ReviewCode { options: options.clone() },
            
            SelectSubagent: SelectSubagent { options: options.clone() },
            
            ValidateImplementation: ValidateImplementation { options: options.clone() },
            
        }
    }
}

// Builder convenience methods
impl_options_convenience_methods!(BamlAsyncClient);

pub static B: BamlAsyncClient = BamlAsyncClient::new();