// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod unions;
mod type_aliases;

pub use classes::*;
pub use enums::*;
pub use unions::*;
pub use type_aliases::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone)]
pub enum Types {

    CheckResult(CheckResult),

    CodeChange(CodeChange),

    CodeExplanation(CodeExplanation),

    CodeReviewFeedback(CodeReviewFeedback),

    CommitMessage(CommitMessage),

    FailureAnalysis(FailureAnalysis),

    ImplementationPlan(ImplementationPlan),

    ImplementationResult(ImplementationResult),

    Issue(Issue),

    LoopDecision(LoopDecision),

    PRDescription(PRDescription),

    ResearchFindings(ResearchFindings),

    StageHandoff(StageHandoff),

    SubagentSelection(SubagentSelection),

    Task(Task),

    TaskBreakdown(TaskBreakdown),

    TestAnalysis(TestAnalysis),

    ValidationResult(ValidationResult),


    NextAction(NextAction),

    TaskComplexity(TaskComplexity),


    Union3KcreateOrKdeleteOrKmodify(Union3KcreateOrKdeleteOrKmodify),

    Union3KcriticalOrKnitpickOrKwarning(Union3KcriticalOrKnitpickOrKwarning),

    Union4KanalyzerOrKbuilderOrKsearcherOrKvalidator(Union4KanalyzerOrKbuilderOrKsearcherOrKvalidator),

    Union6KchoreOrKdocsOrKfeatOrKfixOrKrefactorOrKtest(Union6KchoreOrKdocsOrKfeatOrKfixOrKrefactorOrKtest),

}

impl baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            Types::CheckResult(_) => "CheckResult",

            Types::CodeChange(_) => "CodeChange",

            Types::CodeExplanation(_) => "CodeExplanation",

            Types::CodeReviewFeedback(_) => "CodeReviewFeedback",

            Types::CommitMessage(_) => "CommitMessage",

            Types::FailureAnalysis(_) => "FailureAnalysis",

            Types::ImplementationPlan(_) => "ImplementationPlan",

            Types::ImplementationResult(_) => "ImplementationResult",

            Types::Issue(_) => "Issue",

            Types::LoopDecision(_) => "LoopDecision",

            Types::PRDescription(_) => "PRDescription",

            Types::ResearchFindings(_) => "ResearchFindings",

            Types::StageHandoff(_) => "StageHandoff",

            Types::SubagentSelection(_) => "SubagentSelection",

            Types::Task(_) => "Task",

            Types::TaskBreakdown(_) => "TaskBreakdown",

            Types::TestAnalysis(_) => "TestAnalysis",

            Types::ValidationResult(_) => "ValidationResult",


            Types::NextAction(_) => "NextAction",

            Types::TaskComplexity(_) => "TaskComplexity",


            Types::Union3KcreateOrKdeleteOrKmodify(_) => "Union3KcreateOrKdeleteOrKmodify",

            Types::Union3KcriticalOrKnitpickOrKwarning(_) => "Union3KcriticalOrKnitpickOrKwarning",

            Types::Union4KanalyzerOrKbuilderOrKsearcherOrKvalidator(_) => "Union4KanalyzerOrKbuilderOrKsearcherOrKvalidator",

            Types::Union6KchoreOrKdocsOrKfeatOrKfixOrKrefactorOrKtest(_) => "Union6KchoreOrKdocsOrKfeatOrKfixOrKrefactorOrKtest",


        }
    }
}