// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated union types.

use baml::{BamlEncode, BamlDecode};
use super::*;


/// Generated from: ("create" | "modify" | "delete")
#[derive(Debug, Clone, BamlEncode, BamlDecode, PartialEq, Eq, Hash)]
#[baml(union)]
pub enum Union3KcreateOrKdeleteOrKmodify {

    #[baml(name = "string_create", literal_string = "create")]
    Kcreate,
    
    #[baml(name = "string_modify", literal_string = "modify")]
    Kmodify,
    
    #[baml(name = "string_delete", literal_string = "delete")]
    Kdelete,
    
}

impl AsRef<Union3KcreateOrKdeleteOrKmodify> for Union3KcreateOrKdeleteOrKmodify {
    fn as_ref(&self) -> &Union3KcreateOrKdeleteOrKmodify {
        self
    }
}

impl Default for Union3KcreateOrKdeleteOrKmodify {
    fn default() -> Self {
        
           
            Self::Kcreate
        
    }
}


/// Generated from: ("critical" | "warning" | "nitpick")
#[derive(Debug, Clone, BamlEncode, BamlDecode, PartialEq, Eq, Hash)]
#[baml(union)]
pub enum Union3KcriticalOrKnitpickOrKwarning {

    #[baml(name = "string_critical", literal_string = "critical")]
    Kcritical,
    
    #[baml(name = "string_warning", literal_string = "warning")]
    Kwarning,
    
    #[baml(name = "string_nitpick", literal_string = "nitpick")]
    Knitpick,
    
}

impl AsRef<Union3KcriticalOrKnitpickOrKwarning> for Union3KcriticalOrKnitpickOrKwarning {
    fn as_ref(&self) -> &Union3KcriticalOrKnitpickOrKwarning {
        self
    }
}

impl Default for Union3KcriticalOrKnitpickOrKwarning {
    fn default() -> Self {
        
           
            Self::Kcritical
        
    }
}


/// Generated from: ("searcher" | "analyzer" | "builder" | "validator")
#[derive(Debug, Clone, BamlEncode, BamlDecode, PartialEq, Eq, Hash)]
#[baml(union)]
pub enum Union4KanalyzerOrKbuilderOrKsearcherOrKvalidator {

    #[baml(name = "string_searcher", literal_string = "searcher")]
    Ksearcher,
    
    #[baml(name = "string_analyzer", literal_string = "analyzer")]
    Kanalyzer,
    
    #[baml(name = "string_builder", literal_string = "builder")]
    Kbuilder,
    
    #[baml(name = "string_validator", literal_string = "validator")]
    Kvalidator,
    
}

impl AsRef<Union4KanalyzerOrKbuilderOrKsearcherOrKvalidator> for Union4KanalyzerOrKbuilderOrKsearcherOrKvalidator {
    fn as_ref(&self) -> &Union4KanalyzerOrKbuilderOrKsearcherOrKvalidator {
        self
    }
}

impl Default for Union4KanalyzerOrKbuilderOrKsearcherOrKvalidator {
    fn default() -> Self {
        
           
            Self::Ksearcher
        
    }
}


/// Generated from: ("feat" | "fix" | "docs" | "refactor" | "test" | "chore")
#[derive(Debug, Clone, BamlEncode, BamlDecode, PartialEq, Eq, Hash)]
#[baml(union)]
pub enum Union6KchoreOrKdocsOrKfeatOrKfixOrKrefactorOrKtest {

    #[baml(name = "string_feat", literal_string = "feat")]
    Kfeat,
    
    #[baml(name = "string_fix", literal_string = "fix")]
    Kfix,
    
    #[baml(name = "string_docs", literal_string = "docs")]
    Kdocs,
    
    #[baml(name = "string_refactor", literal_string = "refactor")]
    Krefactor,
    
    #[baml(name = "string_test", literal_string = "test")]
    Ktest,
    
    #[baml(name = "string_chore", literal_string = "chore")]
    Kchore,
    
}

impl AsRef<Union6KchoreOrKdocsOrKfeatOrKfixOrKrefactorOrKtest> for Union6KchoreOrKdocsOrKfeatOrKfixOrKrefactorOrKtest {
    fn as_ref(&self) -> &Union6KchoreOrKdocsOrKfeatOrKfixOrKrefactorOrKtest {
        self
    }
}

impl Default for Union6KchoreOrKdocsOrKfeatOrKfixOrKrefactorOrKtest {
    fn default() -> Self {
        
           
            Self::Kfeat
        
    }
}

