// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod type_aliases;
mod unions;

pub use classes::*;
pub use type_aliases::*;
pub use unions::*;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone)]
pub enum StreamTypes {
    CheckResult(CheckResult),

    CodeChange(CodeChange),

    CodeExplanation(CodeExplanation),

    CodeReviewFeedback(CodeReviewFeedback),

    CommitMessage(CommitMessage),

    FailureAnalysis(FailureAnalysis),

    ImplementationPlan(ImplementationPlan),

    ImplementationResult(ImplementationResult),

    Issue(Issue),

    LoopDecision(LoopDecision),

    PRDescription(PRDescription),

    ResearchFindings(ResearchFindings),

    StageHandoff(StageHandoff),

    SubagentSelection(SubagentSelection),

    Task(Task),

    TaskBreakdown(TaskBreakdown),

    TestAnalysis(TestAnalysis),

    ValidationResult(ValidationResult),
}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            StreamTypes::CheckResult(_) => "CheckResult",

            StreamTypes::CodeChange(_) => "CodeChange",

            StreamTypes::CodeExplanation(_) => "CodeExplanation",

            StreamTypes::CodeReviewFeedback(_) => "CodeReviewFeedback",

            StreamTypes::CommitMessage(_) => "CommitMessage",

            StreamTypes::FailureAnalysis(_) => "FailureAnalysis",

            StreamTypes::ImplementationPlan(_) => "ImplementationPlan",

            StreamTypes::ImplementationResult(_) => "ImplementationResult",

            StreamTypes::Issue(_) => "Issue",

            StreamTypes::LoopDecision(_) => "LoopDecision",

            StreamTypes::PRDescription(_) => "PRDescription",

            StreamTypes::ResearchFindings(_) => "ResearchFindings",

            StreamTypes::StageHandoff(_) => "StageHandoff",

            StreamTypes::SubagentSelection(_) => "SubagentSelection",

            StreamTypes::Task(_) => "Task",

            StreamTypes::TaskBreakdown(_) => "TaskBreakdown",

            StreamTypes::TestAnalysis(_) => "TestAnalysis",

            StreamTypes::ValidationResult(_) => "ValidationResult",
        }
    }
}
