// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{BamlDecode, BamlEncode};

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct CheckResult {
    pub name: String,

    pub passed: bool,

    pub details: Option<String>,
}

impl AsRef<CheckResult> for CheckResult {
    fn as_ref(&self) -> &CheckResult {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct CodeChange {
    pub file_path: String,

    pub action: Union3KcreateOrKdeleteOrKmodify,

    pub description: String,

    pub code: Option<String>,
}

impl AsRef<CodeChange> for CodeChange {
    fn as_ref(&self) -> &CodeChange {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct CodeExplanation {
    pub purpose: String,

    pub how_it_works: String,

    pub key_components: Vec<String>,

    pub dependencies: Vec<String>,

    pub used_by: Vec<String>,
}

impl AsRef<CodeExplanation> for CodeExplanation {
    fn as_ref(&self) -> &CodeExplanation {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct CodeReviewFeedback {
    pub approved: bool,

    pub issues: Vec<Issue>,

    pub suggestions: Vec<String>,
}

impl AsRef<CodeReviewFeedback> for CodeReviewFeedback {
    fn as_ref(&self) -> &CodeReviewFeedback {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct CommitMessage {
    #[baml(name = "type")]
    pub r#type: Union6KchoreOrKdocsOrKfeatOrKfixOrKrefactorOrKtest,

    pub scope: Option<String>,

    pub subject: String,

    pub body: Option<String>,

    pub breaking: bool,
}

impl AsRef<CommitMessage> for CommitMessage {
    fn as_ref(&self) -> &CommitMessage {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct FailureAnalysis {
    pub test_name: String,

    pub error_message: String,

    pub likely_cause: String,

    pub suggested_fix: String,
}

impl AsRef<FailureAnalysis> for FailureAnalysis {
    fn as_ref(&self) -> &FailureAnalysis {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ImplementationPlan {
    pub goal: String,

    pub approach: String,

    pub tasks: Vec<Task>,

    pub risks: Vec<String>,

    pub out_of_scope: Vec<String>,
}

impl AsRef<ImplementationPlan> for ImplementationPlan {
    fn as_ref(&self) -> &ImplementationPlan {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ImplementationResult {
    pub summary: String,

    pub changes: Vec<CodeChange>,

    pub tests_to_run: Vec<String>,

    pub follow_up: Vec<String>,
}

impl AsRef<ImplementationResult> for ImplementationResult {
    fn as_ref(&self) -> &ImplementationResult {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct Issue {
    pub severity: Union3KcriticalOrKnitpickOrKwarning,

    pub file_path: String,

    pub line: Option<i64>,

    pub description: String,

    pub suggestion: Option<String>,
}

impl AsRef<Issue> for Issue {
    fn as_ref(&self) -> &Issue {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct LoopDecision {
    pub action: NextAction,

    pub reasoning: String,

    pub next_task_id: Option<String>,

    pub message: Option<String>,
}

impl AsRef<LoopDecision> for LoopDecision {
    fn as_ref(&self) -> &LoopDecision {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct PRDescription {
    pub title: String,

    pub summary: String,

    pub changes: Vec<String>,

    pub testing: String,

    pub checklist: Vec<String>,
}

impl AsRef<PRDescription> for PRDescription {
    fn as_ref(&self) -> &PRDescription {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ResearchFindings {
    pub summary: String,

    pub relevant_files: Vec<String>,

    pub key_insights: Vec<String>,

    pub patterns: Vec<String>,

    pub open_questions: Vec<String>,
}

impl AsRef<ResearchFindings> for ResearchFindings {
    fn as_ref(&self) -> &ResearchFindings {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct StageHandoff {
    pub from_stage: String,

    pub to_stage: String,

    pub summary: String,

    pub key_artifacts: Vec<String>,

    pub context_for_next: String,

    pub open_items: Vec<String>,
}

impl AsRef<StageHandoff> for StageHandoff {
    fn as_ref(&self) -> &StageHandoff {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct SubagentSelection {
    pub category: Union4KanalyzerOrKbuilderOrKsearcherOrKvalidator,

    pub prompt: String,

    pub timeout_hint: String,
}

impl AsRef<SubagentSelection> for SubagentSelection {
    fn as_ref(&self) -> &SubagentSelection {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct Task {
    pub id: String,

    pub title: String,

    pub description: String,

    pub complexity: TaskComplexity,

    pub depends_on: Vec<String>,

    pub acceptance_criteria: Vec<String>,
}

impl AsRef<Task> for Task {
    fn as_ref(&self) -> &Task {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct TaskBreakdown {
    pub subtasks: Vec<Task>,

    pub estimated_minutes: i64,

    pub blockers: Vec<String>,
}

impl AsRef<TaskBreakdown> for TaskBreakdown {
    fn as_ref(&self) -> &TaskBreakdown {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct TestAnalysis {
    pub summary: String,

    pub passed: i64,

    pub failed: i64,

    pub failures: Vec<FailureAnalysis>,

    pub coverage_notes: Option<String>,
}

impl AsRef<TestAnalysis> for TestAnalysis {
    fn as_ref(&self) -> &TestAnalysis {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ValidationResult {
    pub passed: bool,

    pub checks: Vec<CheckResult>,

    pub blocking_issues: Vec<String>,

    pub recommendations: Vec<String>,
}

impl AsRef<ValidationResult> for ValidationResult {
    fn as_ref(&self) -> &ValidationResult {
        self
    }
}
