// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated enum types.

use baml::{BamlDecode, BamlEncode};

#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode)]

pub enum NextAction {
    Continue,

    Replan,

    Validate,

    Complete,

    AskHuman,
}

impl Default for NextAction {
    fn default() -> Self {
        Self::Continue
    }
}

impl std::fmt::Display for NextAction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Continue => write!(f, "Continue"),

            Self::Replan => write!(f, "Replan"),

            Self::Validate => write!(f, "Validate"),

            Self::Complete => write!(f, "Complete"),

            Self::AskHuman => write!(f, "AskHuman"),
        }
    }
}

impl std::str::FromStr for NextAction {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Continue" => Ok(Self::Continue),

            "Replan" => Ok(Self::Replan),

            "Validate" => Ok(Self::Validate),

            "Complete" => Ok(Self::Complete),

            "AskHuman" => Ok(Self::AskHuman),

            _ => Err(()),
        }
    }
}

impl AsRef<NextAction> for NextAction {
    fn as_ref(&self) -> &NextAction {
        self
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode)]

pub enum TaskComplexity {
    Low,

    Medium,

    High,
}

impl Default for TaskComplexity {
    fn default() -> Self {
        Self::Low
    }
}

impl std::fmt::Display for TaskComplexity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Low => write!(f, "Low"),

            Self::Medium => write!(f, "Medium"),

            Self::High => write!(f, "High"),
        }
    }
}

impl std::str::FromStr for TaskComplexity {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Low" => Ok(Self::Low),

            "Medium" => Ok(Self::Medium),

            "High" => Ok(Self::High),

            _ => Err(()),
        }
    }
}

impl AsRef<TaskComplexity> for TaskComplexity {
    fn as_ref(&self) -> &TaskComplexity {
        self
    }
}
