// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.


/// Wrapper for the `CheckResult` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct CheckResultClassBuilder {
    inner: baml::ClassBuilder,
}

impl CheckResultClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("CheckResult is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `name` field builder.
    pub fn property_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("name")
            .expect("CheckResult.name is statically defined in .baml and should always be present")
    }


    /// Access the `passed` field builder.
    pub fn property_passed(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("passed")
            .expect("CheckResult.passed is statically defined in .baml and should always be present")
    }


    /// Access the `details` field builder.
    pub fn property_details(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("details")
            .expect("CheckResult.details is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `CodeChange` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct CodeChangeClassBuilder {
    inner: baml::ClassBuilder,
}

impl CodeChangeClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("CodeChange is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `file_path` field builder.
    pub fn property_file_path(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("file_path")
            .expect("CodeChange.file_path is statically defined in .baml and should always be present")
    }


    /// Access the `action` field builder.
    pub fn property_action(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("action")
            .expect("CodeChange.action is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("CodeChange.description is statically defined in .baml and should always be present")
    }


    /// Access the `code` field builder.
    pub fn property_code(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("code")
            .expect("CodeChange.code is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `CodeExplanation` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct CodeExplanationClassBuilder {
    inner: baml::ClassBuilder,
}

impl CodeExplanationClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("CodeExplanation is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `purpose` field builder.
    pub fn property_purpose(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("purpose")
            .expect("CodeExplanation.purpose is statically defined in .baml and should always be present")
    }


    /// Access the `how_it_works` field builder.
    pub fn property_how_it_works(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("how_it_works")
            .expect("CodeExplanation.how_it_works is statically defined in .baml and should always be present")
    }


    /// Access the `key_components` field builder.
    pub fn property_key_components(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("key_components")
            .expect("CodeExplanation.key_components is statically defined in .baml and should always be present")
    }


    /// Access the `dependencies` field builder.
    pub fn property_dependencies(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("dependencies")
            .expect("CodeExplanation.dependencies is statically defined in .baml and should always be present")
    }


    /// Access the `used_by` field builder.
    pub fn property_used_by(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("used_by")
            .expect("CodeExplanation.used_by is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `CodeReviewFeedback` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct CodeReviewFeedbackClassBuilder {
    inner: baml::ClassBuilder,
}

impl CodeReviewFeedbackClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("CodeReviewFeedback is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `approved` field builder.
    pub fn property_approved(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("approved")
            .expect("CodeReviewFeedback.approved is statically defined in .baml and should always be present")
    }


    /// Access the `issues` field builder.
    pub fn property_issues(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("issues")
            .expect("CodeReviewFeedback.issues is statically defined in .baml and should always be present")
    }


    /// Access the `suggestions` field builder.
    pub fn property_suggestions(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("suggestions")
            .expect("CodeReviewFeedback.suggestions is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `CommitMessage` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct CommitMessageClassBuilder {
    inner: baml::ClassBuilder,
}

impl CommitMessageClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("CommitMessage is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `r#type` field builder.
    pub fn property_type(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("type")
            .expect("CommitMessage.type is statically defined in .baml and should always be present")
    }


    /// Access the `scope` field builder.
    pub fn property_scope(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("scope")
            .expect("CommitMessage.scope is statically defined in .baml and should always be present")
    }


    /// Access the `subject` field builder.
    pub fn property_subject(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("subject")
            .expect("CommitMessage.subject is statically defined in .baml and should always be present")
    }


    /// Access the `body` field builder.
    pub fn property_body(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("body")
            .expect("CommitMessage.body is statically defined in .baml and should always be present")
    }


    /// Access the `breaking` field builder.
    pub fn property_breaking(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("breaking")
            .expect("CommitMessage.breaking is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `FailureAnalysis` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct FailureAnalysisClassBuilder {
    inner: baml::ClassBuilder,
}

impl FailureAnalysisClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("FailureAnalysis is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `test_name` field builder.
    pub fn property_test_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("test_name")
            .expect("FailureAnalysis.test_name is statically defined in .baml and should always be present")
    }


    /// Access the `error_message` field builder.
    pub fn property_error_message(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("error_message")
            .expect("FailureAnalysis.error_message is statically defined in .baml and should always be present")
    }


    /// Access the `likely_cause` field builder.
    pub fn property_likely_cause(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("likely_cause")
            .expect("FailureAnalysis.likely_cause is statically defined in .baml and should always be present")
    }


    /// Access the `suggested_fix` field builder.
    pub fn property_suggested_fix(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("suggested_fix")
            .expect("FailureAnalysis.suggested_fix is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `ImplementationPlan` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ImplementationPlanClassBuilder {
    inner: baml::ClassBuilder,
}

impl ImplementationPlanClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("ImplementationPlan is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `goal` field builder.
    pub fn property_goal(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("goal")
            .expect("ImplementationPlan.goal is statically defined in .baml and should always be present")
    }


    /// Access the `approach` field builder.
    pub fn property_approach(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("approach")
            .expect("ImplementationPlan.approach is statically defined in .baml and should always be present")
    }


    /// Access the `tasks` field builder.
    pub fn property_tasks(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tasks")
            .expect("ImplementationPlan.tasks is statically defined in .baml and should always be present")
    }


    /// Access the `risks` field builder.
    pub fn property_risks(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("risks")
            .expect("ImplementationPlan.risks is statically defined in .baml and should always be present")
    }


    /// Access the `out_of_scope` field builder.
    pub fn property_out_of_scope(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("out_of_scope")
            .expect("ImplementationPlan.out_of_scope is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `ImplementationResult` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ImplementationResultClassBuilder {
    inner: baml::ClassBuilder,
}

impl ImplementationResultClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("ImplementationResult is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("ImplementationResult.summary is statically defined in .baml and should always be present")
    }


    /// Access the `changes` field builder.
    pub fn property_changes(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("changes")
            .expect("ImplementationResult.changes is statically defined in .baml and should always be present")
    }


    /// Access the `tests_to_run` field builder.
    pub fn property_tests_to_run(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tests_to_run")
            .expect("ImplementationResult.tests_to_run is statically defined in .baml and should always be present")
    }


    /// Access the `follow_up` field builder.
    pub fn property_follow_up(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("follow_up")
            .expect("ImplementationResult.follow_up is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `Issue` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct IssueClassBuilder {
    inner: baml::ClassBuilder,
}

impl IssueClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("Issue is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `severity` field builder.
    pub fn property_severity(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("severity")
            .expect("Issue.severity is statically defined in .baml and should always be present")
    }


    /// Access the `file_path` field builder.
    pub fn property_file_path(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("file_path")
            .expect("Issue.file_path is statically defined in .baml and should always be present")
    }


    /// Access the `line` field builder.
    pub fn property_line(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("line")
            .expect("Issue.line is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("Issue.description is statically defined in .baml and should always be present")
    }


    /// Access the `suggestion` field builder.
    pub fn property_suggestion(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("suggestion")
            .expect("Issue.suggestion is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `LoopDecision` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct LoopDecisionClassBuilder {
    inner: baml::ClassBuilder,
}

impl LoopDecisionClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("LoopDecision is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `action` field builder.
    pub fn property_action(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("action")
            .expect("LoopDecision.action is statically defined in .baml and should always be present")
    }


    /// Access the `reasoning` field builder.
    pub fn property_reasoning(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("reasoning")
            .expect("LoopDecision.reasoning is statically defined in .baml and should always be present")
    }


    /// Access the `next_task_id` field builder.
    pub fn property_next_task_id(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("next_task_id")
            .expect("LoopDecision.next_task_id is statically defined in .baml and should always be present")
    }


    /// Access the `message` field builder.
    pub fn property_message(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("message")
            .expect("LoopDecision.message is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `PRDescription` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct PRDescriptionClassBuilder {
    inner: baml::ClassBuilder,
}

impl PRDescriptionClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("PRDescription is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `title` field builder.
    pub fn property_title(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("title")
            .expect("PRDescription.title is statically defined in .baml and should always be present")
    }


    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("PRDescription.summary is statically defined in .baml and should always be present")
    }


    /// Access the `changes` field builder.
    pub fn property_changes(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("changes")
            .expect("PRDescription.changes is statically defined in .baml and should always be present")
    }


    /// Access the `testing` field builder.
    pub fn property_testing(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("testing")
            .expect("PRDescription.testing is statically defined in .baml and should always be present")
    }


    /// Access the `checklist` field builder.
    pub fn property_checklist(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("checklist")
            .expect("PRDescription.checklist is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `ResearchFindings` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ResearchFindingsClassBuilder {
    inner: baml::ClassBuilder,
}

impl ResearchFindingsClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("ResearchFindings is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("ResearchFindings.summary is statically defined in .baml and should always be present")
    }


    /// Access the `relevant_files` field builder.
    pub fn property_relevant_files(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("relevant_files")
            .expect("ResearchFindings.relevant_files is statically defined in .baml and should always be present")
    }


    /// Access the `key_insights` field builder.
    pub fn property_key_insights(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("key_insights")
            .expect("ResearchFindings.key_insights is statically defined in .baml and should always be present")
    }


    /// Access the `patterns` field builder.
    pub fn property_patterns(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("patterns")
            .expect("ResearchFindings.patterns is statically defined in .baml and should always be present")
    }


    /// Access the `open_questions` field builder.
    pub fn property_open_questions(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("open_questions")
            .expect("ResearchFindings.open_questions is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `StageHandoff` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct StageHandoffClassBuilder {
    inner: baml::ClassBuilder,
}

impl StageHandoffClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("StageHandoff is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `from_stage` field builder.
    pub fn property_from_stage(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("from_stage")
            .expect("StageHandoff.from_stage is statically defined in .baml and should always be present")
    }


    /// Access the `to_stage` field builder.
    pub fn property_to_stage(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("to_stage")
            .expect("StageHandoff.to_stage is statically defined in .baml and should always be present")
    }


    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("StageHandoff.summary is statically defined in .baml and should always be present")
    }


    /// Access the `key_artifacts` field builder.
    pub fn property_key_artifacts(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("key_artifacts")
            .expect("StageHandoff.key_artifacts is statically defined in .baml and should always be present")
    }


    /// Access the `context_for_next` field builder.
    pub fn property_context_for_next(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("context_for_next")
            .expect("StageHandoff.context_for_next is statically defined in .baml and should always be present")
    }


    /// Access the `open_items` field builder.
    pub fn property_open_items(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("open_items")
            .expect("StageHandoff.open_items is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `SubagentSelection` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SubagentSelectionClassBuilder {
    inner: baml::ClassBuilder,
}

impl SubagentSelectionClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("SubagentSelection is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `category` field builder.
    pub fn property_category(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("category")
            .expect("SubagentSelection.category is statically defined in .baml and should always be present")
    }


    /// Access the `prompt` field builder.
    pub fn property_prompt(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("prompt")
            .expect("SubagentSelection.prompt is statically defined in .baml and should always be present")
    }


    /// Access the `timeout_hint` field builder.
    pub fn property_timeout_hint(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("timeout_hint")
            .expect("SubagentSelection.timeout_hint is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `Task` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct TaskClassBuilder {
    inner: baml::ClassBuilder,
}

impl TaskClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("Task is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `id` field builder.
    pub fn property_id(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("id")
            .expect("Task.id is statically defined in .baml and should always be present")
    }


    /// Access the `title` field builder.
    pub fn property_title(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("title")
            .expect("Task.title is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("Task.description is statically defined in .baml and should always be present")
    }


    /// Access the `complexity` field builder.
    pub fn property_complexity(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("complexity")
            .expect("Task.complexity is statically defined in .baml and should always be present")
    }


    /// Access the `depends_on` field builder.
    pub fn property_depends_on(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("depends_on")
            .expect("Task.depends_on is statically defined in .baml and should always be present")
    }


    /// Access the `acceptance_criteria` field builder.
    pub fn property_acceptance_criteria(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("acceptance_criteria")
            .expect("Task.acceptance_criteria is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `TaskBreakdown` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct TaskBreakdownClassBuilder {
    inner: baml::ClassBuilder,
}

impl TaskBreakdownClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("TaskBreakdown is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `subtasks` field builder.
    pub fn property_subtasks(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("subtasks")
            .expect("TaskBreakdown.subtasks is statically defined in .baml and should always be present")
    }


    /// Access the `estimated_minutes` field builder.
    pub fn property_estimated_minutes(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("estimated_minutes")
            .expect("TaskBreakdown.estimated_minutes is statically defined in .baml and should always be present")
    }


    /// Access the `blockers` field builder.
    pub fn property_blockers(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("blockers")
            .expect("TaskBreakdown.blockers is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `TestAnalysis` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct TestAnalysisClassBuilder {
    inner: baml::ClassBuilder,
}

impl TestAnalysisClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("TestAnalysis is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("TestAnalysis.summary is statically defined in .baml and should always be present")
    }


    /// Access the `passed` field builder.
    pub fn property_passed(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("passed")
            .expect("TestAnalysis.passed is statically defined in .baml and should always be present")
    }


    /// Access the `failed` field builder.
    pub fn property_failed(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("failed")
            .expect("TestAnalysis.failed is statically defined in .baml and should always be present")
    }


    /// Access the `failures` field builder.
    pub fn property_failures(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("failures")
            .expect("TestAnalysis.failures is statically defined in .baml and should always be present")
    }


    /// Access the `coverage_notes` field builder.
    pub fn property_coverage_notes(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("coverage_notes")
            .expect("TestAnalysis.coverage_notes is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `ValidationResult` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ValidationResultClassBuilder {
    inner: baml::ClassBuilder,
}

impl ValidationResultClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("ValidationResult is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `passed` field builder.
    pub fn property_passed(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("passed")
            .expect("ValidationResult.passed is statically defined in .baml and should always be present")
    }


    /// Access the `checks` field builder.
    pub fn property_checks(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("checks")
            .expect("ValidationResult.checks is statically defined in .baml and should always be present")
    }


    /// Access the `blocking_issues` field builder.
    pub fn property_blocking_issues(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("blocking_issues")
            .expect("ValidationResult.blocking_issues is statically defined in .baml and should always be present")
    }


    /// Access the `recommendations` field builder.
    pub fn property_recommendations(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("recommendations")
            .expect("ValidationResult.recommendations is statically defined in .baml and should always be present")
    }

}

