// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated enum builder wrappers for type-safe value access.


/// Wrapper for the `NextAction` enum builder.
///
/// Provides type-safe method access to values defined in the schema.
/// Access values via methods: `builder.ValueName()`

pub struct NextActionEnumBuilder {
    inner: baml::EnumBuilder,
}

impl NextActionEnumBuilder {
    /// Create wrapper from runtime EnumBuilder.
    pub(crate) fn new(inner: baml::EnumBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying EnumBuilder.
    pub fn inner(&self) -> &baml::EnumBuilder {
        &self.inner
    }

    /// Get the enum as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("NextAction is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Value Accessors (1:1 with schema value names)
    // =========================================================================


    /// Access the `Continue` value builder.
    pub fn value_Continue(&self) -> baml::EnumValueBuilder {
        self.inner.get_value("Continue")
            .expect("NextAction.Continue is statically defined in .baml and should always be present")
    }


    /// Access the `Replan` value builder.
    pub fn value_Replan(&self) -> baml::EnumValueBuilder {
        self.inner.get_value("Replan")
            .expect("NextAction.Replan is statically defined in .baml and should always be present")
    }


    /// Access the `Validate` value builder.
    pub fn value_Validate(&self) -> baml::EnumValueBuilder {
        self.inner.get_value("Validate")
            .expect("NextAction.Validate is statically defined in .baml and should always be present")
    }


    /// Access the `Complete` value builder.
    pub fn value_Complete(&self) -> baml::EnumValueBuilder {
        self.inner.get_value("Complete")
            .expect("NextAction.Complete is statically defined in .baml and should always be present")
    }


    /// Access the `AskHuman` value builder.
    pub fn value_AskHuman(&self) -> baml::EnumValueBuilder {
        self.inner.get_value("AskHuman")
            .expect("NextAction.AskHuman is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `TaskComplexity` enum builder.
///
/// Provides type-safe method access to values defined in the schema.
/// Access values via methods: `builder.ValueName()`

pub struct TaskComplexityEnumBuilder {
    inner: baml::EnumBuilder,
}

impl TaskComplexityEnumBuilder {
    /// Create wrapper from runtime EnumBuilder.
    pub(crate) fn new(inner: baml::EnumBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying EnumBuilder.
    pub fn inner(&self) -> &baml::EnumBuilder {
        &self.inner
    }

    /// Get the enum as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("TaskComplexity is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Value Accessors (1:1 with schema value names)
    // =========================================================================


    /// Access the `Low` value builder.
    pub fn value_Low(&self) -> baml::EnumValueBuilder {
        self.inner.get_value("Low")
            .expect("TaskComplexity.Low is statically defined in .baml and should always be present")
    }


    /// Access the `Medium` value builder.
    pub fn value_Medium(&self) -> baml::EnumValueBuilder {
        self.inner.get_value("Medium")
            .expect("TaskComplexity.Medium is statically defined in .baml and should always be present")
    }


    /// Access the `High` value builder.
    pub fn value_High(&self) -> baml::EnumValueBuilder {
        self.inner.get_value("High")
            .expect("TaskComplexity.High is statically defined in .baml and should always be present")
    }

}

